### ISSUE TITLE
Tools bar

### ISSUE THREAD

**Issue by omerozerf** [EmreBeratKR/LazyCoroutines#1]
Please embed "EmreBeratKR" into the Tools section.

<img width="410" alt="image" src="https://github.com/EmreBeratKR/LazyCoroutines/assets/104875927/0ee93c2d-5551-413b-a37d-92b33b08b68e">

**Comment by EmreBeratKR** [comment]
Fixed: https://github.com/EmreBeratKR/LazyCoroutines/commit/36afcf766ee5e6392d29c93cc0291bf9eab1231a
